### ISSUE TITLE
Can't specify permission scope during authorization

### ISSUE THREAD

**Issue by adituriya** [deeja/LinkedInDeveloperToolkit#1]
Would you add the following function to `WebOAuthAuthorization.cs`

```
public void BeginAuthorize(Uri callback, IDictionary<string, string> requestParameters)
{
    this.Consumer.Channel.Send(this.Consumer.PrepareRequestUserAuthorization(callback, requestParameters, null));
}
```

This allows extended permissions to be requested during authorization.
See https://developer.linkedin.com/documents/authentication#granting

Works fine for me but would be nice to have in the main package.

**Comment by deeja** [comment]
Yeah i can. Wont be for a few days as I am on holiday. If you want send me
a pull request with your chnages.

Dan

**Comment by deeja** [comment]
Fixed by Paul Irwin
