### ISSUE TITLE
Requesting permissions

### ISSUE THREAD

**Issue by rhar** [deeja/LinkedInDeveloperToolkit#2]
Hi,
  How do I request extended permissions such as email using the LinkedInDeveloperToolkit?

Robert,

**Comment by paulirwin** [comment]
Robert,

I added a commit a while back that enables this, as I needed the same thing. Check out the GetLinkedInServiceDescriptionWithAdditionalScope static method. 

Here's the commit that added that capability: https://github.com/deeja/LinkedInDeveloperToolkit/commit/f93e5989713c7129bd0b15fec326b79e95467f34

Let me know if you have any issues.

Thanks!
Paul

**Comment by paulirwin** [comment]
You will also need to call LinkedInOAuthClient.RequestExtraAuthData("email",
ProfileField.EmailAddress) so that the "email" key is added to the extraData dictionary.

**Comment by rhar** [comment]
Thanks Paul, I look forward to trying it out.

**Comment by rhar** [comment]
Hi Paul,

   Thanks for the info but I am having lots of trouble with the new version that I downloaded from the (github). I cannot re-compile the library or use any of the samples. When I try to link the new dll into my app I get the following error:-

   The type or namespace name 'WebOAuthAuthorization' could not be found (are you missing a using directive or an assembly reference?)    C:\aSimplr\Project\SimplrBiz\Biz5\Core\uBizLinkedIn.cs               

I have searched the web looking for ‘'WebOAuthAuthorization'´but cannot find anything. Can you lend any assistance?

Regards,

Robert

Chief Technical Officer

The Irish Software Company

Web:   http://www.tisc.ie www.tisc.ie

email:  mailto:Robert@tisc.ie Robert@tisc.ie

Main Office: 353 (0)1 4948011

Support: 353 (0)45 864484

Cell: 353 (0)87 9930350

**Comment by paulirwin** [comment]
Robert, I just tried grabbing the latest code and it won't build for me either, but I'm getting different errors primarily in the tests project. deeja, can you take a look?

**Comment by deeja** [comment]
Yeah, I will take a look. Haven't been around much lately...

**Comment by rhar** [comment]
Hi Paul,

  Thank goodness it’s not just me. Hopefully deeja will be able to fix it quickly.

Regards,

Robert

Chief Technical Officer

The Irish Software Company

Web:   http://www.tisc.ie www.tisc.ie

email:  mailto:Robert@tisc.ie Robert@tisc.ie

Main Office: 353 (0)1 4948011

Support: 353 (0)45 864484

Cell: 353 (0)87 9930350

**Comment by rhar** [comment]
Thanks Daniel.

Regards,

Robert

Chief Technical Officer

The Irish Software Company

Web:   http://www.tisc.ie www.tisc.ie

email:  mailto:Robert@tisc.ie Robert@tisc.ie

Main Office: 353 (0)1 4948011

Support: 353 (0)45 864484

Cell: 353 (0)87 9930350

**Comment by deeja** [comment]
Hey guys.

So I have changed a fair amount of the Test library configuration so they
are no longer on .Net 4.5 and don't conflict. Don't know why they were
anyway.
 .Net 4 is the way to go so sticking with it for the moment.

The tests generally compile but only 25-30% pass. The others are most
likely integration test connection issues. I didn't write them and haven't
had the time to through them tonight.

I didn't do anything to the core library really apart from reapply
references to make sure it compiled properly.
I will be away this weekend so if you find an issue let me know but don't
hold your breath for a fix before Tuesday.

**Comment by rhar** [comment]
Hi Daniel,

  Hope you had a nice weekend away. Any further update on progress for the WebOAuthorization linkage problem?

Regards,

Robert

Chief Technical Officer

The Irish Software Company

Web:   http://www.tisc.ie www.tisc.ie

email:  mailto:Robert@tisc.ie Robert@tisc.ie

Main Office: 353 (0)1 4948011

Support: 353 (0)45 864484

Cell: 353 (0)87 9930350

**Comment by deeja** [comment]
Haven't had a chance to check it out yet. See if my latest commits had any
effect on it.

**Comment by mickdelaney** [comment]
@rhar i think the issue you have is the nuget package is out of date relative to the source code. 

WebOAuthorization no longer exists in this repository. 

I got the toolkit to work by using LinkedInOAuthClient
and supplying the needed dependencies. 

you dont need to use WebOAuthorization  (it doesnt exist in any case). 

Have a look here: 
https://github.com/deeja/LinkedInDeveloperToolkit/blob/master/src/Samples/FunctionExamples/Classes/ServiceLookup.cs

I have a service that's called by a method in my mvc controller when i want a token:

  public class LinkedInAuthService : ILinkedInAuth
    {
        readonly LinkedInOAuthClient _client;

```
    public LinkedInAuthService(LinkedInOAuthClient client)
    {
        _client = client;
    }

    public void Authenticate(HttpContextBase ctx, string returnUrl)
    {
        _client.RequestAuthentication(ctx, new Uri(returnUrl));
    }

    public bool Verify(HttpContextBase ctx)
    {
        try
        {
            var response = _client.VerifyAuthentication(ctx);

            if (response.Error == null)
            {
                return false;
            }

            return true;
        }
        catch (Exception)
        {
            return false;
        }
    }
}
```

This redirects and stores the token against the user using an implementation of: IAccessTokenStorage

let me know if you need any more help.

**Comment by rhar** [comment]
Hi Daniel,

  I wonder if you can help me with this. Using the LinkedInDevToolkit I can connect, authorize and read my details. However I cannot read any updates. No error occurs, only the result returned is empty. 

```
                                                                            {

                                                                            ServiceProviderDescription s = new ServiceProviderDescription();

                                                                            var authorization = new WebOAuthAuthorization(new TokenManager() , AccessToken);

                                                                            LinkedInService service = new LinkedInService(authorization);



                                                                            var b = NetworkUpdateTypes.All;



                                                                            var recs = service.GetNetworkUpdates(b);

                                                                            }
```

The recs var is always empty. Any ideas or suggestions you might have would be welcomed.

Regards,

Robert

Chief Technical Officer

Zzyzxl Ltd.

Web:   http://www.tisc.ie/ www.tisc.ie

email:  mailto:Robert@zzyzxl.ie Robert@zzyzxl.ie

Main Office: 353 (0)45 868845

Support: 353 (0)45 864484

Cell: 353 (0)87 6676534
